### ISSUE TITLE
使用ReactTransitionGroup实现React动画效果

### ISSUE THREAD

**Issue by luckyhalley** [luckyhalley/blog#3]
在前端领域，关于动画效果的实现，无外乎两种方式，一种方式是使用CSS3的transition或animation属性实现动画效果，另一种则是通过JavaScript改变DOM元素的属性并在时间变化过程中产生的动画效果。

> HTML5增加的Canvas和SVG标签也可以用来实现动画效果，Canvas动画的本质是通过JavaScript不断重绘画布实现的，而SVG除了可以使用类似操作DOM的方式实现动画，也可以用同步多媒体集成语言（SMIL）来描述动画，关于SMIL可以参考规范文档：http://www.w3.org/TR/REC-smil/。

需要思考的是React改变了基于DOM操作的编程方式，由于React组件生命周期的存在，使用JavaScript直接操作DOM元素来完成动画效果在React项目中并不是一种很好的选择。

为了实现动画效果，React官方提供了2个组件：ReactTransitionGroup和ReactCSSTransitionGroup。ReactTransitionGroup是底层组件，而ReactCSSTransitionGroup组件则是基于ReactTransitionGroup，并提供了执行CSS 3 transition和animation动画的一种简单的方式。

## 示例代码
首先看一个例子：
```JavaScript
import React, { Component } from 'react';  
import './App.css';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';
class App extends Component {  
    constructor(props) {  
        super(props);
        this.state = {items: [{id: 1, title: 'Todo1'}, {id: 2, title: 'Todo2'}]};			//默认数据
        this.addItem = this.addItem.bind(this);
    }
    addItem() {
        let key = this.state.items[this.state.items.length - 1].id + 1;
        const newItems = this.state.items.concat([{id: key, title: 'Todo' + key}]);	//添加项
        this.setState({items: newItems});								//同步state
    }
    removeItem(i) {
        const newItems = this.state.items.slice();
        newItems.splice(i, 1);										//删除项
        this.setState({items: newItems});								//同步state
    }
    render() {
        const items = this.state.items.map((item, i) => (
        <li key={item.id} onClick={() => this.removeItem(i)}>
            {item.title}
        </li>
        ));
        return (
            <div className="App">
                <h2>React CSS动画示例</h2>
                <button onClick={this.addItem}>增加新项</button>
                <ul>
                <ReactCSSTransitionGroup
                    transitionName="react-animaition"
                    transitionAppear={true}
                    transitionAppearTimeout={500}
                    transitionEnterTimeout={500}
                    transitionLeaveTimeout={500}>
                    {items}
                </ReactCSSTransitionGroup>
                </ul>
            </div>
        );
    }
}
```
对于曾经有过AngularJS开发经验的开发者来说，这段代码看上去并不会那么陌生，ReactCSSTransitionGroup组件的灵感正是来自于AngularJS动画指令ng-animate。

当子组件初始化挂载到ReactCSSTransitionGroup中，或者对ReactCSSTransitionGroup做添加项，移除项操作时，特殊的CSS样式类被添加到子组件上，为了让ReactCSSTransitionGroup内的子组件产生动画效果，就可以利用这些样式类编写对应的CSS 3动画：

```CSS
.react-animaition-appear {
    opacity: 0.01;
}
.react-animaition-appear.react-animaition-appear-active {
    opacity: 1;
    transition: opacity 500ms ease-in;
}
.react-animaition-enter {
    opacity: 0.01;
}
.react-animaition-enter.react-animaition-enter-active {
    opacity: 1;
    transition: opacity 500ms ease-in;
}
.react-animaition-leave {
    opacity: 1;
}
.react-animaition-leave.react-animaition-leave-active {
    opacity: 0.01;
    transition: opacity 500ms ease-in;
}
```
## ReactCSSTransitionGroup组件的参数配置

详细看一下ReactCSSTransitionGroup组件的参数配置：

* transitionName
> 附加在子组件上的CSS样式名都是基于transitionName生成的，当以字符串形式提供这个参数时，transitionName会作为附加样式名的前缀生成对应样式名，也可以使用对象字面量的方式，固定所有或者部分附加样式名，例如：“transitionName={{enter: 'enter', enterActive: 'enterActive'}}”。

* transitionAppear
> 定义是否在子组件初始化挂载阶段加入附加样式，默认值是false。

* transitionEnter
> 定义是否在新项目进入ReactCSSTransitionGroup组件时加入附加样式，由于transitionEnter以及transitionLeave的默认值都是true，实际在上例中已经省略。

* transitionLeave
> 定义是否在项目被移除ReactCSSTransitionGroup组件时加入附加样式。

* transitionAppearTimeout
> 定义子组件初始化挂载阶段加入附加样式后，到从子组件上移除这个附加样式所经过的时间。

* transitionEnterTimeout
> 定义对添加到ReactCSSTransitionGroup内的子组件加入附加样式后，到从这个子组件上移除这个附加样式所经过的时间。

* transitionLeaveTimeout
> 定义将要从ReactCSSTransitionGroup内移除的子组件加入附加样式后，到从这个子组件上移除这个附加样式所经过的时间，并且随后这个子组件会从DOM中被移除。

## ReactTransitionGroup提供特殊生命周期

前文已经说明ReactCSSTransitionGroup是基于ReactTransitionGroup实现的，作为底层组件，ReactTransitionGroup提供特殊生命周期hooks函数，ReactCSSTransitionGroup正是利用这些函数，对子组件各阶段附加了对应的CSS样式名。由ReactTransitionGroup提供的这些特殊生命周期函数有：

* componentWillAppear(callback)
> 组件被初始化挂载到ReactTransitionGroup内的componentDidMount阶段被调用，阻止其它动画发生直到其回调函数被执行。

* componentDidAppear()
> componentWillAppear回调函数被执行后调用。

* componentWillEnter(callback)
> 组件添加到ReactTransitionGroup内的componentDidMount阶段被调用，阻止其它动画发生直到其回调函数被执行。

* componentDidEnter()
> componentWillEnter回调函数被执行后调用。

* componentWillLeave(callback)
> 组件从ReactTransitionGroup内移除时调用，尽管子组件被移除，ReactTransitionGroup仍然在DOM保持直到回调被执行。

* componentDidLeave()
> 组件componentWillUnmount阶段调用。

接下来就可以利用ReactTransitionGroup提供的这些特殊生命周期函数，自己定制动画效果了，也可以引入第三方动画库如Velocity.js来实现动画效果，具体可以参考React官方文档。

> React官方提供的ReactTransitionGroup只是针对基本的动画需求提出的一种解决方案，目前也已经有一些高度定制化的动画组件，如https://github.com/chenglou/react-motion，可以自行参考使用。
